Etsy1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .import views
app_name = 'esty'
urlpatterns = [
    url(r'^platformes/',include('platformes.urls',namespace='platformes')),
    url(r'.*$',views.index,name='index')
]

platformes/urls.py
from django.conf.urls import url
from . import views

app_name = 'platformes'

urlpatterns = [
    url(r'^index/$',views.index,name='index'),
url(r'^file_update/$',views.file_update,name='file_update'),
url(r'^tatalGoods/$',views.tatalGoods,name='tatalGoods'),
]

platformes/models.py
from django.db import models

# Create your models here.
class GoodsManager(models.Manager):
    pass

class Goods(models.Model):
    id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255,null=True)
    price_ago=models.FloatField(null=True)
    price_now = models.FloatField(null=True)
    feedback=models.FloatField(null=True)
    favorited=models.FloatField(null=True)
    img=models.FileField(upload_to='static/es_platform/img',null=True)
    good_url=models.CharField(max_length=255,null=True)
    shop_name=models.CharField(max_length=255,null=True)
    shop_url=models.CharField(max_length=255,null=True)
    shipping=models.CharField(max_length=255,null=True)
    label_one=models.CharField(max_length=255,null=True)
    label_two=models.CharField(max_length=255,null=True)
    source_time=models.CharField(max_length=255,null=True)

    goods_manage=GoodsManager()

platformes/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import models
# Create your views here.
def index(request):
    if request.method == "GET":
        return render(request,'platformes/index.html')
    else:
        return HttpResponse('这并非是一个get请求')
#看看文件上传上去的格式
def file_update(request):
    if request.method == "GET":
        return render(request,'platformes/file_update.html')
    else:
        print("request.path", request.path)
        print("request.POST", request.POST)
        print("request.file", request.FILES)
        title = request.POST['title']
        price_ago = request.POST['price_ago']
        price_now = request.POST['price_now']
        feedback = request.POST['feedback']
        favorited = request.POST['favorited']
        img = request.FILES['img']

        ever_good=models.Goods.goods_manage.create(title=title,price_now=price_now,price_ago=price_ago,feedback=feedback,favorited=favorited,img=img)
        print("商品为：",ever_good)
        return render(request,"platformes/index.html")

def tatalGoods(request):
    # print("request.path", request.path)
    # print("request.method", request.method)
    try:#从搜索框过来
        content=request.GET['search']
        price_low = request.GET["price_low"]
        price_high = request.GET["price_high"]

        # 获取查询的商品类型
        # 分页展示的时候，前端不会再一次传递内容参数，所以if一下，为空的话就用session获取
        if (content or price_low or price_high):
            request.session['search'] = content
            request.session['price_low'] = price_low
            request.session['price_high'] = price_high

        else:
            content=request.session['search']
            price_low=request.session['price_low']
            price_high = request.session['price_high']

        #处理价格
        try:#拥有最低高价
            # print("有高低")
            all_goods = models.Goods.goods_manage.filter(title__icontains=content,price_now__gt=price_low,price_now__lt=price_high).order_by('feedback')
            currentPage, all_goods ,paginator,page_obj= page(request, all_goods, 20)
            return render(request, 'platformes/index.html', {'all_goods': all_goods, 'currentPage': currentPage,'paginator':paginator,'page_obj':page_obj})
        except:#没有最高只有最低
            try:
                # print("有低")
                all_goods = models.Goods.goods_manage.filter(title__icontains=content,price_now__gt=price_low).order_by('-feedback')
                currentPage, all_goods ,paginator,page_obj = page(request, all_goods, 20)
                return render(request, 'platformes/index.html',
                              {'all_goods': all_goods, 'currentPage': currentPage,'paginator':paginator,'page_obj':page_obj})
            except:
                try:
                    # print("有高")
                    all_goods = models.Goods.goods_manage.filter(title__icontains=content,price_now__lt=price_high).order_by('-feedback')
                    currentPage, all_goods ,paginator ,page_obj= page(request, all_goods, 20)
                    return render(request, 'platformes/index.html',
                                  {'all_goods': all_goods, 'currentPage': currentPage,'paginator':paginator,'page_obj':page_obj})
                except:
                    # print("没有高低")
                    all_goods = models.Goods.goods_manage.filter(title__icontains=content).order_by('-feedback')
                    if all_goods:
                        print("能查询到数据")
                        currentPage, all_goods ,paginator, page_obj= page(request, all_goods, 20)
                        return render(request, 'platformes/index.html',{'all_goods': all_goods, 'currentPage': currentPage,'paginator':paginator,'page_obj':page_obj})
                    else:
                        print("没有数据")
                        return render(request, 'platformes/index.html')
    except:
        print("不是从搜索框中过来的，从url地址或者a标签")
        content = request.session['search']
        price_low = request.session['price_low']
        price_high = request.session['price_high']
        if(content or price_low or price_high):
            print(request.session['search'])
            print(request.session['price_low'])
            print('all over')
            print(request.session['price_high'])
            try:  # 拥有最低高价
                # print("有高低")
                all_goods = models.Goods.goods_manage.filter(title__icontains=content, price_now__gt=price_low,
                                                             price_now__lt=price_high).order_by('feedback')
                currentPage, all_goods, paginator,page_obj = page(request, all_goods, 20)
                return render(request, 'platformes/index.html',
                              {'all_goods': all_goods, 'currentPage': currentPage, 'paginator': paginator,'page_obj':page_obj})
            except:  # 没有最高只有最低
                try:
                    # print("有低")
                    all_goods = models.Goods.goods_manage.filter(title__icontains=content,
                                                                 price_now__gt=price_low).order_by('-feedback')
                    currentPage, all_goods, paginator,page_obj = page(request, all_goods, 20)
                    return render(request, 'platformes/index.html',
                                  {'all_goods': all_goods, 'currentPage': currentPage, 'paginator': paginator,'page_obj':page_obj})
                except:
                    try:
                        # print("有高")
                        all_goods = models.Goods.goods_manage.filter(title__icontains=content,
                                                                     price_now__lt=price_high).order_by('-feedback')
                        currentPage, all_goods, paginator,page_obj = page(request, all_goods, 20)
                        return render(request, 'platformes/index.html',
                                      {'all_goods': all_goods, 'currentPage': currentPage, 'paginator': paginator,'page_obj':page_obj})
                    except:
                        # print("没有高低")
                        all_goods = models.Goods.goods_manage.filter(title__icontains=content).order_by('-feedback')
                        if all_goods:
                            print("能查询到数据")
                            currentPage, all_goods, paginator,page_obj = page(request, all_goods, 20)
                            return render(request, 'platformes/index.html',
                                          {'all_goods': all_goods, 'currentPage': currentPage, 'paginator': paginator,'page_obj':page_obj})
                        else:
                            print("没有数据")
                            return render(request, 'platformes/index.html')
        else:
            all_goods = models.Goods.goods_manage.filter().order_by('-feedback')

            currentPage, all_goods  ,paginator,page_obj= page(request, all_goods, 20)
            return render(request, 'platformes/index.html', {'all_goods': all_goods, 'currentPage': currentPage,'paginator':paginator,'page_obj':page_obj})





#对所有的商品进行分页展示
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
#传递对象值和每页显示的记录个数
def page(request,obj,item):
    # 获取Book数据表中的所有记录
    # 生成paginator对象,定义每页显示20条记录
    paginator = Paginator(obj, item)

    # 从前端获取当前的页码数,默认为1
    page = request.GET.get('page', 1)

    # 把当前的页码数转换成整数类型
    currentPage = int(page)

    #如果页数过多时，做进一步处理
    if paginator.num_pages >10:
        if currentPage-3<1:
            pageRange = range(1,6)
        elif currentPage+3 > paginator.num_pages:
            pageRange=range(currentPage-3,paginator.num_pages+1)
        else:
            pageRange=range(currentPage -3,currentPage+3)
    else:
        pageRange = paginator.page_range
    try:
        print(page)
        book_list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        book_list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        book_list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return currentPage,book_list,pageRange,paginator

platformes/templates/platformes/file_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文件上传</title>
</head>
<body>
<form action="{% url 'platformes:file_update'%}"
                          method="POST" enctype="multipart/form-data">
    {% csrf_token %}
                        <div class="form_group">
							<label>标题</label>
							<input type="text" name="title">
						</div>
                        <div class="form_group">
							<label>原价</label>
							<input type="text" name="price_ago">
						</div>
                        <div class="form_group">
							<label>上传头像：</label>
							<input type="file" name="img">
						</div>

						<div class="form_group">
							<label>现价：</label>
							<input type="text" name="price_now">
						</div>

						<div class="form_group">
							<label>评论数：</label>
							<input type="text" name="feedback">
						</div>
                        <div class="form_group">
							<label>收藏数：</label>
							<input type="text" name="favorited">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
</body>
</html>

platformes/templates/platformes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Etsy搜索平台</title>
    <!--切记jQuery一定要在bootstrap之前，否则，会报错-->
    <!--引入jq-->
    <script src="/static/es_platform/jquery/jquery-1.12.4.min.js"></script>
    <!--引入bootstrap的CSS样式和js样式-->
    <link href="/static/es_platform/css/bootstrap.css" rel="stylesheet" type="text/css"
          media="all"/>
    <script src="/static/es_platform/js/bootstrap.js"></script>

    <style>
        .left_div{
            background:indianred;
        }
        .right_div{
            background:lightgoldenrodyellow;
        }
        .search_div{
            background:#ccc;
            width:100%;
            height:300px;

        }
        .message_div{
            background:#999;
            width:100%;
            height:10000px;
        }
        .shopping_name,.prcie_title{
            display:inline-block;
        }
        .search_content{
            width:400px;
            height:52px;

        }
        input{
            border-radius: 5px;
            border-color: #66B1D2;
        }
        body{
            font-size:12px;
        }

    </style>
</head>
<body>
<h1>etsy 搜索平台</h1>
<div class=".container-fluid">
    <div class="row">
        <div class="col-xs-6 col-md-2 left_div">
            <div class="mainContent">展示</div>
             <div class="row row1 scroll-pane">
                    <form action="/smart_user/goods_list/" method="POST">
                    <label class="checkbox"><input type="checkbox"
                                                   name="kw_color"
                                                   checked=""
                                                   value="白"><i></i>White
                    </label>
                    <label class="checkbox"><input type="checkbox"
                                                   name="kw_color"
                                                   value="粉"><i></i>Pink
                    </label>
                    <label class="checkbox"><input type="checkbox"
                                                   name="kw_color"
                                                   value="金"><i></i>
                        Gold</label>
                    <label class="checkbox"><input type="checkbox"
                                                   name="kw_color"
                                                   value="蓝"><i></i>
                        Blue</label>
                    <label class="checkbox"><input type="checkbox"
                                                   name="kw_color"
                                                   value="橙"><i></i>
                        Orange</label>
                    <label class="checkbox"><input type="checkbox"
                                                   name="kw_color"
                                                   value="黑"
                    ><i></i> Black</label>
                        <input type="submit" value="search">
                    </form>
                </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-10 right_div">
            <div class="row search_div">


                <form action="{% url 'platformes:tatalGoods' %}" method="get">
                    <h3 class="shopping_name">请输入商品名：</h3>
                        <input type="text" name="search" placeholder="search name" class="search_content">
                    <br>
                    <h4 class="prcie_title">请输入价格范围：</h4>
                    最低价:<input type="text" name="price_low" placeholder="lowest price">
                    最高价:<input type="text" name="price_high" placeholder="high price"><br>
                    <input type="submit" value="search">
                </form>


            </div>

            <div class="row message_div">
                
            <table class="table invoice-table table-striped table-hover info">
                <thead>
                <tr class="success">
                    <th>序号</th>
                    <th>图片</th>
                    <th>商电名</th>
                    <th>标题</th>
                    <th>价格</th>
                    <th>评论数</th>
                    <th>收藏人数</th>
                    <th>标签</th>
                    <th>操作</th>
                </tr>
                </thead>


                <tbody>
                 {% if all_goods %}
                {% for shopping in all_goods %}
                <tr class="active">
                    <td style="width:8%;text-align:center;line-height:7px">
                        {{forloop.counter}}
                    </td>


                    <td style="width:25%">
                        <a href="{{shopping.good_url}}">
                        <img src="/{{shopping.img}}" alt="no"
                             style="width:100px;height:100px"> </a>
                    </td>

                        <td style="width:16%">
                            <a href="{{shopping.shop_url}}">
                            {{shopping.shop_name }}</a>
                        </td>


                        <td style="width:20%">
                            <a href="{{shopping.good_url}}">

                                <strong>{{shopping.title }}</strong>
                            </a>
                        </td>

                    <td style="width:20%">
                        <strong><span>现价：</span>${{shopping.price_now }}</strong><br>
                        <strong><span>原价：</span>${{shopping.price_ago }}</strong>
                    </td>

                    <td style="width:15%">{{shopping.feedback}}</td>
                    <td style="width:15%">{{shopping.favorited}}</td>

                    <td style="width:15%">
                        <span>{{shopping.label_one }}</span>
                        <span>{{shopping.label_two}}</span>
                    </td>

                    <td><a
                            href={{shopping.good_url}}>查看商品详情</a>
                    </td>
                </tr>
                {% endfor %}
               {% else %}
                <br><br><h3>please search again another words</h3><br>
                {% endif %}
                </tbody>

</table>
                
                <!--对商品进行分页-->
                <ul class="pagination" id="pager">
        {#上一页按钮开始#}
        {# 如果当前页有上一页#}
        {% if all_goods.has_previous %}
            {#  当前页的上一页按钮正常使用#}
            <li class="previous"><a href="/platformes/tatalGoods/?page={{ all_goods.previous_page_number }}" class="active_num">上一页</a></li>
        {% else %}
            {# 当前页的不存在上一页时,上一页的按钮不可用#}
            <li class="previous disabled"><a href="#">上一页</a></li>
        {% endif %}
        {#上一页按钮结束#}
                    {# 添加首页 #}
                    <li class="last" ><a href="/platformes/tatalGoods/?page=1" class="active_num">首页</a></li>

        {# 页码开始#}
        {% for num in paginator %}

            {% if num == currentPage %}
                <li class="item active" ><a href="/platformes/tatalGoods/?page={{ num }}" class="active_num">{{ num }}</a></li>
            {% else %}
                <li class="item"><a href="/platformes/tatalGoods/?page={{ num }}" class="active_num">{{ num }}</a></li>

            {% endif %}
        {% endfor %}

                    {# 添加最后一页#}
                    <li class="last" ><a href="/platformes/tatalGoods/?page={{ page_obj.num_pages }}" class="active_num">尾页</a></li>

        {#页码结束#}
        {# 下一页按钮开始#}
        {% if all_goods.has_next %}
            <li class="next"><a href="/platformes/tatalGoods/?page={{ all_goods.next_page_number }}" class="active_num">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
        {# 下一页按钮结束#}
    </ul>
            </div>
        </div>
    </div>

</div>






<!--<button id="publish">按钮</button>-->
<script>

    $(".active_num").click(function(){
     alert("发表成功")
        alert($(this).text())
    })


//    $(".active_num").click(function(){
//
//        var url = "/platformes/tatalGoods/";
//        var data = $('.content').val();
//        alert(data);
//        $.ajax({
//            type : "get",
////            async : false,  //同步请求
//            url : url,
//            data :{'data':data},
//            success:function(dates){
//                alert(dates);
//                console.log(dates);
//
//                $(".mainContent").html(dates);//要刷新的div
//            },
//            error: function() {
//               // alert("失败，请稍后再试！");
//            }
//        });
//    });

</script>

</body>
</html>